version: 2

project_name: experia-v10-exporter

builds:
  - id: experia-v10-exporter
    main: ./cmd/experia-v10-exporter
    binary: experia-v10-exporter
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-s -w']

archives:
  - id: default
    formats: [tar.gz]
    files: [README.md]
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: git

# Publish Docker images to GHCR using goreleaser's docker support (buildx).
# The workflow should ensure GHCR_TOKEN is available as a secret.
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: docker/Dockerfile
    use: buildx
