version: 2

project_name: experia-v10-exporter

builds:
  - id: experia-v10-exporter
    main: ./cmd/experia-v10-exporter
    binary: experia-v10-exporter
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-s -w']

archives:
  - id: default
    formats: [tar.gz]
    files: [README.md]
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: git

# Publish Docker images to GHCR using goreleaser's docker support.
# The workflow must ensure GHCR credentials are available in GHCR_TOKEN.
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: docker/Dockerfile
    use: buildx
version: 2

project_name: experia-v10-exporter

builds:
  - id: experia-v10-exporter
    main: ./cmd/experia-v10-exporter
    binary: experia-v10-exporter
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-s -w']

archives:
  - id: default
    formats: [tar.gz]
    files: [README.md]
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: git

# Deprecated fields removed: snapshot.name_template and archives.builds
# This is a minimal goreleaser v2 config suitable for snapshot checks.

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: docker/Dockerfile
    use: buildx
    platforms:
      - linux/amd64
      - linux/arm64
    skip_push: false
    skip_push: false
