version: 2

project_name: experia-v10-exporter

builds:
  - id: experia-v10-exporter
    main: ./cmd/experia-v10-exporter
    binary: experia-v10-exporter
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: ['-s -w']

archives:
  - id: default
    formats: [tar.gz]
    files: [README.md]
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: git

# Publish Docker images to GHCR using goreleaser's dockers_v2 support (buildx).
# The workflow should ensure GHCR_TOKEN is available as a secret.
dockers_v2:
  - dockerfile: docker/Dockerfile
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
