version: "3.8"

services:
  experia-v10-exporter:
    # Use a configurable image so we can point at a locally-built image during dev
    image: ${EXPERIA_V10_IMAGE:-ghcr.io/grammatonic/experia-v10-exporter:local}
    environment:
      - EXPERIA_V10_LISTEN_ADDR=${EXPERIA_V10_LISTEN_ADDR:-:9100}
      - EXPERIA_V10_TIMEOUT=${EXPERIA_V10_TIMEOUT:-10s}
      - EXPERIA_V10_ROUTER_IP=${EXPERIA_V10_ROUTER_IP:-192.168.2.254}
      - EXPERIA_V10_ROUTER_USERNAME=${EXPERIA_V10_ROUTER_USERNAME}
      - EXPERIA_V10_ROUTER_PASSWORD=${EXPERIA_V10_ROUTER_PASSWORD}
    ports:
      - "${EXPERIA_V10_PORT:-9100}:${EXPERIA_V10_PORT:-9100}"
    restart: unless-stopped
