name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  snapshot:
    name: Snapshot (test goreleaser)
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |-
            ~/.cache/go-build
            ~/.cache/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install goreleaser (install only)
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run goreleaser (snapshot)
        run: goreleaser release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release (tag)
    runs-on: ubuntu-latest
    needs: snapshot
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |-
            ~/.cache/go-build
            ~/.cache/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install goreleaser (install only)
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GHCR
        if: ${{ secrets.GHCR_TOKEN != '' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Run goreleaser (release)
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
