name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  snapshot:
    name: Snapshot (test goreleaser)
    runs-on: ubuntu-latest
    outputs:
      has_ghcr: ${{ steps.check-ghcr.outputs.has_ghcr }}
    if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install goreleaser (install only)
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GHCR token available
        id: check-ghcr
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          if [ -n "$GHCR_TOKEN" ]; then
            echo "has_ghcr=true" >> $GITHUB_OUTPUT
          else
            echo "has_ghcr=false" >> $GITHUB_OUTPUT
          fi
      - name: Check goreleaser config
        run: goreleaser check --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run goreleaser (snapshot)
        run: goreleaser release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release (tag)
    runs-on: ubuntu-latest
    needs: snapshot
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install goreleaser (install only)
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GHCR
        if: needs.snapshot.outputs.has_ghcr == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set up QEMU (for multi-arch builds)
        if: needs.snapshot.outputs.has_ghcr == 'true'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: needs.snapshot.outputs.has_ghcr == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Restore buildx cache from GHCR
        if: needs.snapshot.outputs.has_ghcr == 'true'
        uses: docker/build-push-action@v4
        with:
          load: false
          cache-from: "type=registry,ref=ghcr.io/${{ github.repository }}:buildx-cache"
      - name: Export GHCR_TOKEN for goreleaser
        if: needs.snapshot.outputs.has_ghcr == 'true'
        run: echo "GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}" >> $GITHUB_ENV
      - name: Run goreleaser (release)
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      - name: Save buildx cache to GHCR
        if: needs.snapshot.outputs.has_ghcr == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-to: "type=registry,ref=ghcr.io/${{ github.repository }}:buildx-cache,mode=max"
