name: Trivy scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy filesystem & image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image name (lowercase)
        run: |
          # Lowercase the full repository (owner/repo) to form a valid container repo name
          # ${GITHUB_REPOSITORY,,} lowercases the whole string (bash expansion)
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:trivy-scan" >> $GITHUB_ENV

      - name: Build Docker image for scan
        run: |
          echo "Building image $IMAGE"
          docker build -t "$IMAGE" -f docker/Dockerfile . || true

      - name: Trivy scan filesystem
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          format: json
          output: trivy-filesystem.json

      - name: Trivy scan image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE }}
          format: json
          output: trivy-image.json

      - name: Upload Trivy results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: |
            trivy-filesystem.json
            trivy-image.json
